spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa283h2bgIK6HRIV357
            client-secret: V1XUZGhIYGvpZSRQnVd3mOxLeOY4z7jycEBUfAOR
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-548882.okta.com/oauth2/default
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_schedule
    username: root
    password: kienkun1990
  jpa:
      hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: create
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect